import React, { useState } from "react";
import { motion, AnimatePresence } from "motion/react";
import { X, Info, Heart, FileText, Settings, LogOut, Download, ShieldCheck, Moon, Sun, Monitor, Eye, EyeOff, MessageSquare, ArrowRight, Smartphone, Banknote, QrCode, Camera, Upload, CheckCircle2, Sparkles } from "lucide-react";
import { Ring } from "./ui/Ring";
import { Profile, Transaction } from "@/src/types";
import { cn } from "@/src/lib/utils";
import { format } from "date-fns";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

interface ProfileDrawerProps {
  isOpen: boolean;
  onClose: () => void;
  profile: Profile;
  settledTransactions: Transaction[];
  activeBorrowings: Transaction[];
  onUpdateProfile: (updates: Partial<Profile>) => void;
  onLogout: () => void;
  onSettle: (id: string) => void;
  onOpenHeartHub: () => void;
}

export function ProfileDrawer({ 
  isOpen, 
  onClose, 
  profile, 
  settledTransactions, 
  activeBorrowings,
  onUpdateProfile, 
  onLogout,
  onSettle,
  onOpenHeartHub
}: ProfileDrawerProps) {
  const [isReturnChatOpen, setIsReturnChatOpen] = useState(false);
  const [isLegalOpen, setIsLegalOpen] = useState(false);
  const [selectedBorrowing, setSelectedBorrowing] = useState<Transaction | null>(null);
  const [settlementMode, setSettlementMode] = useState<'select' | 'upi' | 'cash'>('select');
  const [isUPIRedirecting, setIsUPIRedirecting] = useState(false);
  const [evidenceImage, setEvidenceImage] = useState<string | null>(null);

  const generatePDF = (transaction: Transaction) => {
    const doc = new jsPDF();
    
    doc.setFontSize(22);
    doc.text("Vishwaspay Settlement Receipt", 20, 20);
    
    doc.setFontSize(12);
    doc.text(`Receipt ID: ${transaction.id}`, 20, 30);
    doc.text(`Date: ${format(new Date(), 'PPP')}`, 20, 36);
    
    autoTable(doc, {
      startY: 45,
      head: [['Description', 'Details']],
      body: [
        ['Lender', transaction.lender_name],
        ['Borrower', transaction.borrower_name],
        ['Amount', `INR ${transaction.amount.toLocaleString()}`],
        ['Status', 'Settled'],
        ['Settled Date', transaction.settled_at ? format(new Date(transaction.settled_at), 'PPP') : 'N/A'],
      ],
      theme: 'striped',
      headStyles: { fillColor: [0, 77, 77] }
    });
    
    doc.text("This is a legally binding settlement receipt generated by Vishwaspay.", 20, doc.internal.pageSize.height - 30);
    doc.text("Compliant with IT Act 2000 digital signature guidelines.", 20, doc.internal.pageSize.height - 24);
    
    doc.save(`Vishwaspay_Receipt_${transaction.id}.pdf`);
  };

  const handleUPIClick = () => {
    setIsUPIRedirecting(true);
    setTimeout(() => {
      if (selectedBorrowing) {
        onSettle(selectedBorrowing.id);
        setIsUPIRedirecting(false);
        setSelectedBorrowing(null);
        setSettlementMode('select');
      }
    }, 2500);
  };

  const handleManualConfirm = () => {
    if (selectedBorrowing) {
      onSettle(selectedBorrowing.id);
      setSelectedBorrowing(null);
      setSettlementMode('select');
      setEvidenceImage(null);
    }
  };

  const handleImageUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      const reader = new FileReader();
      reader.onloadend = () => setEvidenceImage(reader.result as string);
      reader.readAsDataURL(file);
    }
  };

  return (
    <AnimatePresence>
      {isOpen && (
        <>
          <motion.div 
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            onClick={onClose}
            className="fixed inset-0 bg-black/60 backdrop-blur-sm z-40"
          />
          <motion.div 
            initial={{ x: "100%" }}
            animate={{ x: 0 }}
            exit={{ x: "100%" }}
            transition={{ type: "spring", damping: 25, stiffness: 200 }}
            className={cn(
              "fixed top-0 right-0 h-full w-full max-w-md z-50 overflow-y-auto p-8 shadow-2xl transition-colors duration-300",
              "bg-background text-foreground"
            )}
          >
            <div className="flex justify-between items-center mb-10">
              <h2 className="text-3xl font-serif font-bold">Profile</h2>
              <button onClick={onClose} className="p-2 hover:bg-foreground/10 rounded-full transition-colors">
                <X size={24} />
              </button>
            </div>

            <div className="space-y-8">
              {/* Trust Score Panel */}
              <div className="art-frame p-6 rounded-3xl relative overflow-hidden">
                <div className="flex justify-between items-start mb-4">
                  <h3 className="text-sm font-bold uppercase tracking-widest opacity-60">Trust Score</h3>
                  <div className="group relative">
                    <Info size={18} className="opacity-40 cursor-help" />
                    <div className="absolute right-0 top-full mt-2 w-48 p-3 art-frame rounded-xl text-[10px] opacity-0 group-hover:opacity-100 transition-opacity pointer-events-none z-10">
                      Your score is calculated based on repayment history, timeliness, and community endorsements. Higher scores unlock lower platform fees.
                    </div>
                  </div>
                </div>
                <div className="flex justify-center py-4">
                  <Ring 
                    value={profile.trust_score} 
                    min={300} 
                    max={900} 
                    size={160} 
                    strokeWidth={10}
                    label="Score"
                  />
                </div>
              </div>

              {/* Return Money Chat Button */}
              <button 
                onClick={() => setIsReturnChatOpen(true)}
                className="w-full p-6 art-frame rounded-3xl flex items-center justify-between group hover:bg-foreground/5 transition-all"
              >
                <div className="flex items-center gap-4">
                  <div className="w-12 h-12 bg-foreground/5 rounded-2xl flex items-center justify-center text-foreground">
                    <MessageSquare size={24} />
                  </div>
                  <div className="text-left">
                    <h3 className="font-bold">Return Money Chat</h3>
                    <p className="text-[10px] opacity-40 uppercase tracking-widest">Settle your borrowings</p>
                  </div>
                </div>
                <ArrowRight size={20} className="text-foreground group-hover:translate-x-1 transition-transform" />
              </button>

              {/* Hearts Panel */}
              <div className="art-frame p-6 rounded-3xl flex justify-between items-center shadow-sm">
                <div>
                  <h3 className="text-sm font-bold uppercase tracking-widest opacity-60 mb-1 text-foreground">Heart Balance</h3>
                  <div className="flex items-center gap-2">
                    <Heart size={24} className="text-amber-accent" fill="currentColor" />
                    <span className="text-3xl font-serif font-bold text-foreground">{profile.hearts_balance}</span>
                  </div>
                </div>
                <button 
                  onClick={onOpenHeartHub}
                  className="px-4 py-2 bg-amber-accent text-black font-bold rounded-xl text-xs hover:bg-amber-accent/80 transition-colors shadow-lg"
                >
                  Earn / Buy
                </button>
              </div>

              {/* Settlement Vault */}
              <div className="space-y-4">
                <h3 className="text-sm font-bold uppercase tracking-widest opacity-60 px-2">Settlement Vault</h3>
                <div className="art-frame p-6 rounded-[2.5rem] shadow-inner-vault">
                  <div className="space-y-4 max-h-60 overflow-y-auto pr-2 custom-scrollbar">
                    {settledTransactions.length > 0 ? settledTransactions.map(tx => (
                      <div key={tx.id} className="bg-foreground/5 p-4 rounded-2xl flex justify-between items-center border border-foreground/5 hover:bg-foreground/10 transition-colors group">
                        <div className="flex items-center gap-3">
                          <div className="w-10 h-10 bg-foreground/5 rounded-xl flex items-center justify-center text-foreground">
                            <FileText size={20} />
                          </div>
                          <div>
                            <p className="text-sm font-bold">{tx.lender_id === profile.id ? tx.borrower_name : tx.lender_name}</p>
                            <p className="text-[10px] opacity-40 uppercase tracking-widest">
                              {tx.settled_at ? format(new Date(tx.settled_at), 'MMM dd, yyyy') : 'N/A'} • ₹{tx.amount.toLocaleString()}
                            </p>
                          </div>
                        </div>
                        <button 
                          onClick={() => generatePDF(tx)}
                          className="p-2 bg-foreground/5 hover:bg-foreground hover:text-background rounded-lg transition-all text-foreground"
                          title="Download Legal Receipt"
                        >
                          <Download size={18} />
                        </button>
                      </div>
                    )) : (
                      <div className="text-center py-10 px-4">
                        <div className="w-16 h-16 bg-foreground/5 rounded-full flex items-center justify-center mx-auto mb-4 border border-foreground/5">
                          <Sparkles size={24} className="opacity-20" />
                        </div>
                        <p className="text-xs font-serif italic opacity-40 leading-relaxed">
                          "Your financial history is empty. Complete a handshake to see it here."
                        </p>
                      </div>
                    )}
                  </div>
                </div>
              </div>

              {/* Settings & Compliance */}
              <div className="space-y-4">
                <h3 className="text-sm font-bold uppercase tracking-widest opacity-60 mb-4 px-2">Preferences</h3>
                
                {/* Theme Toggle */}
                <div className="art-frame p-4 rounded-2xl">
                  <div className="flex items-center gap-3 mb-4">
                    <Sun size={18} className="opacity-60" />
                    <span className="text-sm font-medium">Theme Preference</span>
                  </div>
                  <div className="grid grid-cols-3 gap-2">
                    {(['dark', 'light', 'system'] as const).map((t) => (
                      <button
                        key={t}
                        onClick={() => onUpdateProfile({ theme_preference: t })}
                        className={cn(
                          "py-2 rounded-xl text-[10px] uppercase tracking-widest font-bold transition-all",
                          profile.theme_preference === t 
                            ? "bg-teal-accent text-white" 
                            : "bg-foreground/5 opacity-40 hover:bg-foreground/10"
                        )}
                      >
                        {t}
                      </button>
                    ))}
                  </div>
                </div>

                {/* Privacy Toggle */}
                <button 
                  onClick={() => onUpdateProfile({ privacy_mode: profile.privacy_mode === 'public' ? 'private' : 'public' })}
                  className="w-full flex items-center justify-between p-4 art-frame rounded-2xl hover:bg-foreground/5 transition-colors"
                >
                  <div className="flex items-center gap-3">
                    {profile.privacy_mode === 'public' ? <Eye size={18} className="text-teal-accent" /> : <EyeOff size={18} className="text-amber-accent" />}
                    <div className="text-left">
                      <p className="text-sm font-medium">{profile.privacy_mode === 'public' ? 'Public Mode' : 'Private Mode'}</p>
                      <p className="text-[10px] opacity-40">{profile.privacy_mode === 'public' ? 'Searchable via Phone/UPI' : 'Invite-only via Trust Link'}</p>
                    </div>
                  </div>
                  <div className={cn(
                    "w-10 h-5 rounded-full relative transition-colors",
                    profile.privacy_mode === 'public' ? "bg-teal-accent" : "bg-foreground/10"
                  )}>
                    <motion.div 
                      animate={{ x: profile.privacy_mode === 'public' ? 22 : 2 }}
                      className="absolute top-1 w-3 h-3 bg-white rounded-full"
                    />
                  </div>
                </button>

                <button className="w-full flex items-center justify-between p-4 art-frame rounded-2xl hover:bg-foreground/5 transition-colors">
                  <div className="flex items-center gap-3">
                    <Settings size={18} className="opacity-60" />
                    <span className="text-sm">App Preferences</span>
                  </div>
                </button>
                <button 
                  onClick={() => setIsLegalOpen(true)}
                  className="w-full flex items-center justify-between p-4 art-frame rounded-2xl hover:bg-foreground/5 transition-colors"
                >
                  <div className="flex items-center gap-3">
                    <ShieldCheck size={18} className="opacity-60" />
                    <span className="text-sm">Legal & Privacy (IT Act)</span>
                  </div>
                </button>
                <button 
                  onClick={onLogout}
                  className="w-full flex items-center justify-between p-4 art-frame rounded-2xl hover:bg-red-500/10 transition-colors group"
                >
                  <div className="flex items-center gap-3">
                    <LogOut size={18} className="text-red-500/60 group-hover:text-red-500" />
                    <span className="text-sm text-red-500/60 group-hover:text-red-500">Unlink Google Account</span>
                  </div>
                </button>
              </div>
            </div>
          </motion.div>
        </>
      )}

      {/* Legal & Privacy Overlay */}
      <AnimatePresence>
        {isLegalOpen && (
          <motion.div
            initial={{ opacity: 0, x: "100%" }}
            animate={{ opacity: 1, x: 0 }}
            exit={{ opacity: 0, x: "100%" }}
            className={cn(
              "fixed inset-0 z-[100] p-8 overflow-y-auto transition-colors duration-300",
              "bg-background text-foreground"
            )}
          >
            <div className="max-w-2xl mx-auto">
              <div className="flex justify-between items-center mb-12">
                <button onClick={() => setIsLegalOpen(false)} className="p-2 hover:bg-foreground/10 rounded-full">
                  <X size={24} />
                </button>
                <div className="text-right">
                  <h2 className="text-3xl font-serif font-bold">Legal Act</h2>
                  <p className="text-[8px] uppercase tracking-[0.3em] opacity-40 font-bold">Policies & Guidelines</p>
                </div>
              </div>

              <div className="space-y-12 pb-20">
                <section className="space-y-4">
                  <h3 className="text-2xl font-serif font-bold border-b border-foreground/10 pb-2">1. P2P Handshake Protocol</h3>
                  <p className="text-sm leading-relaxed opacity-80">
                    Vishwaspay operates strictly as a digital ledger for peer-to-peer (P2P) social agreements. The application provides a platform for individuals to record and track informal financial handshakes within their trusted social circles. 
                  </p>
                  <div className="p-4 bg-foreground/5 rounded-xl border-l-4 border-teal-accent">
                    <p className="text-xs font-bold uppercase tracking-widest opacity-60 mb-1">Compliance Note</p>
                    <p className="text-xs italic">
                      Vishwaspay does not store user funds, facilitate direct money transfers through its own servers, or act as a banking intermediary. All financial settlements occur directly between users via external third-party payment systems.
                    </p>
                  </div>
                </section>

                <section className="space-y-4">
                  <h3 className="text-2xl font-serif font-bold border-b border-foreground/10 pb-2">2. Data Sovereignty</h3>
                  <p className="text-sm leading-relaxed opacity-80">
                    We prioritize the security and privacy of your financial interactions. All user data recorded within the Vishwaspay ecosystem is encrypted using industry-standard protocols.
                  </p>
                  <p className="text-sm leading-relaxed opacity-80">
                    Your data is utilized exclusively for the calculation of your internal "Trust Score," which serves as a metric of financial discipline and reliability within the app. We do not sell or share your personal financial records with external credit bureaus or marketing agencies.
                  </p>
                </section>

                <section className="space-y-4">
                  <h3 className="text-2xl font-serif font-bold border-b border-foreground/10 pb-2">3. Social Lending Compliance</h3>
                  <p className="text-sm leading-relaxed opacity-80">
                    Vishwaspay is a Non-NBFC (Non-Banking Financial Company) digital record-keeping tool. It is designed to promote financial discipline, transparency, and social trust among peers.
                  </p>
                  <div className="p-4 bg-foreground/5 rounded-xl border-l-4 border-amber-accent">
                    <p className="text-xs font-bold uppercase tracking-widest opacity-60 mb-1">Legal Status</p>
                    <p className="text-xs italic">
                      This platform is not an unauthorized lending platform. It does not provide credit, loans, or financial products. It merely digitizes the age-old practice of informal social lending, providing a clear record of agreements to prevent misunderstandings.
                    </p>
                  </div>
                </section>

                <div className="pt-10 text-center opacity-30">
                  <p className="text-[10px] uppercase tracking-[0.2em] font-bold">Compliant with IT Act 2000</p>
                  <p className="text-[8px] mt-1">Digital Ledger Certification • v1.0.4</p>
                </div>
              </div>
            </div>
          </motion.div>
        )}
      </AnimatePresence>

      {/* Return Money Chat Overlay */}
      <AnimatePresence>
        {isReturnChatOpen && (
            <motion.div
              initial={{ x: "100%" }}
              animate={{ x: 0 }}
              exit={{ x: "100%" }}
              className={cn(
                "fixed inset-0 z-[60] p-8 overflow-y-auto transition-colors duration-300",
                "bg-background text-foreground"
              )}
            >
              <div className="max-w-md mx-auto">
                <div className="flex justify-between items-center mb-10">
                  <div className="flex items-center gap-3">
                    <button onClick={() => setIsReturnChatOpen(false)} className="p-2 hover:bg-foreground/10 rounded-full">
                      <X size={24} />
                    </button>
                    <h2 className="text-2xl font-serif font-bold">Borrowings</h2>
                  </div>
                </div>

              <div className="space-y-4">
                {activeBorrowings.length > 0 ? activeBorrowings.map(tx => (
                  <button 
                    key={tx.id}
                    onClick={() => {
                      setSelectedBorrowing(tx);
                      setSettlementMode('select');
                    }}
                    className="w-full p-6 art-frame rounded-[2rem] flex items-center justify-between hover:bg-foreground/5 transition-all text-left"
                  >
                    <div>
                      <p className="text-2xl font-serif font-bold">₹{tx.amount.toLocaleString()}</p>
                      <p className="text-xs opacity-40">Owed to {tx.lender_name}</p>
                    </div>
                    <div className="w-10 h-10 bg-foreground/5 rounded-full flex items-center justify-center text-foreground">
                      <ArrowRight size={20} />
                    </div>
                  </button>
                )) : (
                  <div className="text-center py-20 art-frame rounded-[2rem] border-dashed border-foreground/10">
                    <p className="opacity-40 font-serif italic">No active borrowings. You're debt-free!</p>
                  </div>
                )}
              </div>
            </div>
          </motion.div>
        )}
      </AnimatePresence>

      {/* Settlement Modal */}
      <AnimatePresence>
        {selectedBorrowing && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="fixed inset-0 bg-black/80 backdrop-blur-md z-[70] flex items-center justify-center p-6"
          >
            <motion.div
              initial={{ scale: 0.9, y: 20 }}
              animate={{ scale: 1, y: 0 }}
              className="w-full max-w-md art-frame p-8 rounded-[3rem] relative overflow-hidden"
            >
              <button 
                onClick={() => setSelectedBorrowing(null)}
                className="absolute top-6 right-6 p-2 hover:bg-foreground/10 rounded-full"
              >
                <X size={20} />
              </button>

              <div className="text-center mb-8">
                <h3 className="text-sm font-bold uppercase tracking-widest opacity-40 mb-2">Settling Debt</h3>
                <p className="text-4xl font-serif font-bold">₹{selectedBorrowing.amount.toLocaleString()}</p>
                <p className="text-xs opacity-60 mt-1">To {selectedBorrowing.lender_name}</p>
              </div>

              {settlementMode === 'select' && (
                <div className="grid grid-cols-1 gap-4">
                  <button 
                    onClick={() => setSettlementMode('upi')}
                    className="flex items-center gap-6 p-6 art-frame rounded-[2rem] hover:bg-foreground/5 transition-all text-left group"
                  >
                    <div className="w-16 h-16 bg-teal-accent/10 rounded-2xl flex items-center justify-center text-teal-accent group-hover:scale-110 transition-transform">
                      <Smartphone size={32} />
                    </div>
                    <div>
                      <h3 className="font-bold text-lg">Digital Payment</h3>
                      <p className="text-sm opacity-40">UPI, QR Code</p>
                    </div>
                  </button>

                  <button 
                    onClick={() => setSettlementMode('cash')}
                    className="flex items-center gap-6 p-6 art-frame rounded-[2rem] hover:bg-foreground/5 transition-all text-left group"
                  >
                    <div className="w-16 h-16 bg-amber-accent/10 rounded-2xl flex items-center justify-center text-amber-accent group-hover:scale-110 transition-transform">
                      <Banknote size={32} />
                    </div>
                    <div>
                      <h3 className="font-bold text-lg">Manual Payment</h3>
                      <p className="text-sm opacity-40">Physical Cash</p>
                    </div>
                  </button>
                </div>
              )}

              {settlementMode === 'upi' && (
                <div className="space-y-6 text-center">
                  <div className="p-8 art-frame rounded-[2rem] border-dashed border-foreground/10 inline-block mx-auto relative group cursor-pointer" onClick={handleUPIClick}>
                    <QrCode size={160} className="opacity-20 group-hover:text-teal-accent transition-colors" />
                    <div className="absolute inset-0 flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity">
                      <div className="bg-teal-accent text-white px-4 py-2 rounded-xl text-[10px] font-bold uppercase tracking-widest">Pay via UPI</div>
                    </div>
                  </div>
                  <p className="text-[10px] uppercase tracking-widest opacity-40">Scan to pay {selectedBorrowing.lender_name}</p>
                  
                  {isUPIRedirecting && (
                    <motion.div 
                      initial={{ opacity: 0, y: 10 }}
                      animate={{ opacity: 1, y: 0 }}
                      className="flex items-center justify-center gap-3 text-teal-accent font-bold text-sm"
                    >
                      <motion.div
                        animate={{ rotate: 360 }}
                        transition={{ repeat: Infinity, duration: 1, ease: "linear" }}
                        className="w-4 h-4 border-2 border-teal-accent border-t-transparent rounded-full"
                      />
                      Redirecting to UPI App...
                    </motion.div>
                  )}

                  <button onClick={() => setSettlementMode('select')} className="w-full py-4 art-frame rounded-2xl font-bold uppercase tracking-widest text-xs">Back</button>
                </div>
              )}

              {settlementMode === 'cash' && (
                <div className="space-y-6">
                  <div className="space-y-4">
                    <div className="p-4 art-frame rounded-2xl">
                      <p className="text-[10px] uppercase tracking-widest opacity-40 mb-1">Receiver Contact</p>
                      <p className="font-bold">+91 98765 43210</p>
                    </div>

                    <div className="space-y-2">
                      <label className="text-[10px] uppercase tracking-widest opacity-40 ml-2">Proof of Payment</label>
                      <div className="relative">
                        <input 
                          type="file" 
                          accept="image/*" 
                          onChange={handleImageUpload}
                          className="hidden" 
                          id="settlement-upload" 
                        />
                        <label 
                          htmlFor="settlement-upload"
                          className={cn(
                            "w-full flex flex-col items-center justify-center p-8 art-frame rounded-[2rem] border-dashed border-foreground/10 cursor-pointer hover:bg-foreground/5 transition-all",
                            evidenceImage && "border-teal-accent bg-teal-accent/5"
                          )}
                        >
                          {evidenceImage ? (
                            <>
                              <CheckCircle2 size={32} className="text-teal-accent mb-2" />
                              <span className="text-xs font-bold text-teal-accent uppercase tracking-widest">Receipt Attached</span>
                            </>
                          ) : (
                            <>
                              <Upload size={32} className="opacity-20 mb-2" />
                              <span className="text-xs font-bold opacity-40 uppercase tracking-widest">Upload Receipt/Photo</span>
                            </>
                          )}
                        </label>
                      </div>
                    </div>
                  </div>

                  <div className="flex gap-3">
                    <button onClick={() => setSettlementMode('select')} className="flex-1 py-4 art-frame rounded-2xl font-bold uppercase tracking-widest text-xs">Back</button>
                    <button onClick={handleManualConfirm} className="flex-[2] py-4 bg-amber-accent text-black rounded-2xl font-bold uppercase tracking-widest text-xs glow-amber">Confirm Return</button>
                  </div>
                </div>
              )}
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>
    </AnimatePresence>
  );
}
